Revised Election-DB Schema
input-output-hk/catalyst-core pull request #145
Opened 2022-12-12 08:41 UTC by stevenj

This should be a backward-compatible revision of the DB Schema used for Vit-SS but expanded to handle general elections, not just funds.

The election-db crate is intended to be self contained, such that DB logic is only contained in this crate.  
The crate does not handle migrations, but it does check if the db schema it was built against is correct with respect to the db schema in the database,

This schema is only intended to work on postgres, but it is intended in future that this crate may actually create a generic election information data source, so that we could retrieve this data from multiple data sources (web 2 and web 3) without changing the consuming code.

`config_table.rs` is intentionally incomplete.  It is an example of how the db operations should be encapsulated fully internally to this crate.  It will be completed in a further round of work to this crate, and not this PR.

There is a test to ensure the schema validation works,  but its not great and I am open to suggestions of how we test it in CICD.
It checks if the schema known to the crate has been fully applied to the connected DB.
Tests we would need to fully test it:
1. Test all combinations of  db connection strings, env vars, and ,env files work as expected (Valid, invalid and not set).  Also needs to test that Parameter has priority over env var which has priority over the  .env file.  And that when an error is returned, its meaningful and sensible.
2. Test that when the migrations are only partially applied, that is detected and an error returned listing the missing migrations.
3. Test that when an unknown migration is applied to the db, that an error is returned listing the unknown migrations.
4. A combination of 2 & 3.

2022-12-13 14:01 UTC, FelipeRosa requested changes

2022-12-13 14:31 UTC, stevenj commented on src/election-db/src/lib.rs
> +const DATABASE_URL: &str = "DATABASE_URL";
Nitpicks are fine.
Yes, your right.  Hmm,  Maybe "DATABASE_CONN" is better, its the "Database Connection String" after all.
That would be the same for the parameter to the function.

Its already an env var, so it seems a bit redundant to put ENVVAR in the env var name...

2022-12-13 14:32 UTC, stevenj commented on src/election-db/src/lib.rs
> +const DATABASE_URL: &str = "DATABASE_URL";
But the constant name could use it.

2022-12-13 14:32 UTC, stevenj commented on src/election-db/src/lib.rs
> +#[test]
Yes, it should.

2022-12-14 12:30 UTC, minikin submitted a review, later dismissed
Thank you, Steven!

Ps: Should we consider adding a visual representation of DB shema somewhere in the docs?

2022-12-14 14:40 UTC, cameron1024 approved these changes
Looks good - what is the plan regarding errors? There's a bunch of unused warnings, are we plannign to fix them before we merge?

2022-12-14 14:40 UTC, cameron1024 commented on src/election-db/src/lib.rs
> +
I think we should start with `#![warn(clippy::all)]`, or if we wanna go crazy `clippy::pedantic`, since it's usually more work to add it later.

2022-12-14 14:40 UTC, cameron1024 commented on src/election-db/src/schema_check.rs
> +/// Check iof all the migrations we know about are applied, and ONLY those
"iof` typo

2022-12-16 03:31 UTC, stevenj commented on src/election-db/src/config_table.rs
> +    Result<(/*TODO*/), Box<dyn Error + Send + Sync + 'static>> {
You are correct, this whole file is unfinished.  I included it to show the basic structure of keeping all the DB internal details internal.

2022-12-19 06:00 UTC, saibatizoku reviewed
Looks good, maybe needs some info on how to use the cargo make tasks and their importance in the development.md file.

2023-01-09 10:05 UTC, Mr-Leshiy commented on src/election-db/src/config_table.rs
> +struct ConfigKey<'a>{
Agreed, maybe switch into the basic `String` type

2023-01-16 18:07 UTC, cameron1024 commented
Thinking about this more, should it wait until we have a centralized set of types in their own crate? It seems like this would depend on that

2023-02-06 13:50 UTC, cameron1024 commented
Yep, I decided to just create it in the other repo :grin:

2023-02-13 07:06 UTC, stevenj commented
Given the future backend state is going to move towards a distributed object model, and mongo-db may become our main storage engine.  This crate may only have limited use while we are in the transition period.  We may also not make more rust services during this time, and instead make js or python backend services.  

In that light, I think we should just use this crate as the central definition of the schema.  So, it shouldn't need any external dependencies.

Its primary use will be in CI/CD to run migrations when we do a schema update.

2023-02-15 12:29 UTC, FelipeRosa commented
@stevenj I agree. I can remove the logic in this crate and just leave the migrations and schema.rs (for other Rust crates). WDYT?

2023-02-15 20:33 UTC, FelipeRosa commented on Makefiles/db.toml
> +cargo install --git https://github.com/stevenj/diesel_cli_ext --branch all-changes
I believe this has to do with @stevenj wanting to add some feature related to table comments IIRC.

2023-03-17 09:07 UTC, Mr-Leshiy approved these changes
@stevenj @FelipeRosa are we ready to merge this PR ?

2023-03-17 14:36 UTC, FelipeRosa commented
@Mr-Leshiy yes, I just didn't have the time to fix the CI yet.

2023-03-22 15:51 UTC, stevenj commented on Makefiles/db.toml
> +cargo install --git https://github.com/stevenj/diesel_cli_ext --branch all-changes
No longer using this

2023-03-22 15:55 UTC, stevenj commented on src/election-db/src/config_table.rs
> +struct ConfigKey<'a>{
This code is now obsoleted and commented out pending a re-write using the new schema

2023-03-22 15:55 UTC, stevenj commented on src/election-db/src/config_table.rs
> +    Result<(/*TODO*/), Box<dyn Error + Send + Sync + 'static>> {
obsoleted code

2023-03-22 15:57 UTC, stevenj commented on src/election-db/src/lib.rs
> +/// ```
obsoleted code

2023-03-22 15:58 UTC, stevenj commented on src/election-db/src/schema_check.rs
> +            write!(f, "Unknown but applied migrations = {:?}", self.unknown_applied_migrations)?;
obsoleted code

2023-03-22 15:58 UTC, stevenj commented on src/election-db/src/schema_check.rs
> +fn all_migrations_synced<S: MigrationSource<Pg>>(
obsoleted code

2023-03-22 15:59 UTC, stevenj commented on src/election-db/src/schema_check.rs
> +    // using something like the `once_cell` crate.
obsoleted code

2023-03-22 16:45 UTC, merged