Document vitup mock
input-output-hk/catalyst-core pull request #197
Opened 2023-01-03 10:10 UTC by dkijania

2023-01-04 16:21 UTC, kukkok3 commented on book/src/core-testing-doc/api/vitup/mock/Mock.postman_collection.json
> +			},
Some typos *token *unavailable

2023-01-04 16:22 UTC, kukkok3 commented on book/src/core-testing-doc/api/vitup/mock/Mock.postman_collection.json
> +			},
Typo *configured

2023-01-04 16:26 UTC, kukkok3 commented on book/src/core-testing-doc/api/vitup/mock/v0.yaml
> +      operationId: commandAvailableTrue
Typo *token

2023-01-04 16:28 UTC, kukkok3 commented on book/src/core-testing-doc/api/vitup/mock/v0.yaml
> +      operationId: commandAvailableFalse
typo *token

2023-01-04 16:31 UTC, kukkok3 requested changes
LTGM just some typos to fix

2023-01-05 11:10 UTC, minikin approved these changes

2023-01-07 02:13 UTC, stevenj approved these changes

2023-01-09 10:35 UTC, merged