Fix monitor run modes
input-output-hk/catalyst-core pull request #25
Opened 2022-10-13 10:44 UTC by dkijania

Fix monitor runs for vitup and hersir. Remove unnecessary printout and debug info

2022-10-19 12:32 UTC, kukkok3 commented on src/jormungandr/explorer/src/db/indexing.rs
> -                    }
this needs to be reverted

2022-10-19 12:35 UTC, kukkok3 commented on src/jormungandr/testing/mjolnir/src/mjolnir_lib/generators/fragment_generator.rs
>                      &mut self.sender,
this needs to be reverted

2022-10-19 12:39 UTC, kukkok3 requested changes
A couple of files need to be reverted

2022-10-20 13:47 UTC, dkijania commented on src/jormungandr/testing/mjolnir/src/mjolnir_lib/generators/fragment_generator.rs
>                      &mut self.sender,
done

2022-10-20 15:23 UTC, dkijania commented on src/jormungandr/explorer/src/db/indexing.rs
>                      Fragment::Transaction(tx) => {
hmm, i think it is reverted, see latest state of branch:

https://github.com/input-output-hk/catalyst-core/blob/fix_hersir_run_modes/src/jormungandr/explorer/src/db/indexing.rs#L173

2022-10-21 09:09 UTC, kukkok3 approved these changes

2022-10-21 11:35 UTC, merged