feat: implement EventDB tests, update cat-data-service endpoints
input-output-hk/catalyst-core pull request #305
Opened 2023-04-04 08:17 UTC by Mr-Leshiy

# Description

Addded tests for the few queries of the EventDb crate, update api for the cat-data-sevice with the latest specification

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- [ ] queries::snapshot::tests::get_voter_test
- [ ] queries::snapshot::tests::get_delegator_test

2023-04-05 06:47 UTC, stevenj reviewed
Looks good, but...

The Ideascale importer changes.  Did you make those as part of this PR, or have they been introduced when you did a sync with later ideascale importer code than is in main?

2023-04-05 07:34 UTC, Mr-Leshiy commented
@stevenj Going to update with the latest main right now. But how Ideascale importer affect on this PR ? I have not used anything from it.

2023-04-05 12:40 UTC, stevenj requested changes
Sorry discovered issue with the endpoint declarations

2023-04-05 12:40 UTC, stevenj commented on src/cat-data-service/src/service/v1/registration.rs
> +            "/registration/delegations/:stake_public_key/:event",
Same comment as above.
`:event` isn't a path parameter `eid` is an optional query parameter in the format `?eid=77`.

2023-04-05 13:49 UTC, Mr-Leshiy commented on src/cat-data-service/src/service/v1/registration.rs
> +            "/registration/voter/:voting_key/:event",
Hmm, I see.
But what do you think to update API to be OpenAPI ?
I mean I have implemented it in that way, that we have actually two endpoints.
- `/registration/voter/:voting_key`, without provided event id, so using `latest` event
- `/registration/voter/:voting_key/:event`, with event id

2023-04-07 07:13 UTC, saibatizoku approved these changes
LGTM

2023-04-07 07:21 UTC, merged