fix: catalyst-toolbox sve-snapshot command logic
input-output-hk/catalyst-core pull request #354
Opened 2023-05-15 13:53 UTC by FelipeRosa

2023-05-16 20:22 UTC, kukkok3 requested changes
Tested and it looks good. Could you also add 
```
{
  "initial":[
  {
    "fund":
```
at the beginning of the snapshot when generated as json?

2023-05-17 18:02 UTC, kukkok3 requested changes
Outuput is:
```
{
  "initial": {
    "fund":
```    
but is should be
```
 {
  "initial": [ 
  {
    "fund":
```
  missing a **[** after` "initial":`

2023-05-18 06:17 UTC, stevenj approved these changes

2023-05-18 12:44 UTC, kukkok3 approved these changes

2023-05-18 13:14 UTC, merged