feat: adds fund12 cont snapshot
input-output-hk/catalyst-core pull request #692
Opened 2024-04-17 14:25 UTC by kukkok3

# Description

Adding params for fund12 continuos snapshot

Fixes # (issue) _if applicable_

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.
Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**: _if applicable_

- Firmware version:
- Hardware:
- Toolchain:
- SDK:

**List of new dependencies**: _if applicable_

Provide a list of newly added dependencies in this PR, with the description of what are they doing and why do we need them.

- Crate A: description
- Crate B: description

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-04-18 07:22 UTC, coire1 requested changes

2024-04-18 07:22 UTC, coire1 commented on src/event-db/stage_data/prod/00001_fund12_event.sql
> +    'Catalyst Testnet - Fund 12',
Not sure if this is used somewhere, but since this is prod please remove `Testnet`.

2024-04-18 08:03 UTC, coire1 submitted a review, later dismissed
LGTM

2024-04-25 09:33 UTC, kukkok3 commented on .github/workflows/build.yml
> +          path: C:\ProgramData\chocolatey\logs\*
yep, it is on the windows build:)

2024-04-25 22:13 UTC, merged